import type { Drive } from '@/types';
export function defaultDrive(d: Partial<Drive> = {}): Drive {
  const date = d.preferredDates?.[0] || '';
  return {
    id: '',
    company: '',
    role: '',
    location: '',
    ctc: '',
    vacancies: 20,
    description: '',
    cgpa: 7,
    skills: '',
    status: 'SUBMITTED',
    applicants: 0,
    campusId: '',
    campus: '',
    courses: '',
    branches: '',
    graduationYear: '',
    allowedBacklogs: 0,
    backlogRules: 'No active backlogs',
    preferredSkills: '',
    workType: 'Full-time',
    department: '',
    preferredDates: date ? [date] : [],
    deadline: '',
    teamSize: 1,
    hall: true,
    labs: 0,
    rooms: 0,
    systems: 0,
    otherRequirements: '',
    rounds: [],
    workflowVersion: 2,
    workMode: 'On-site',
    responsibilities: '',
    requiredDocuments: 'Resume',
    selectionProcess: '',
    ...d,
  };
}
